Mobile Setup-Head-body Version
ShaddyMore/Mobile-Setup-Head-Middle pull request #1
Opened 2022-11-04 08:04 UTC by ShaddyMore

## Mobile Setup Middle Version

In this project, I did the following:
- Created the header part of the mobile setup
- Created the works section
- Created an about me section
- styled HTML file to look good

2022-11-04 11:01 UTC, OyePriscilla requested changes
Hi @ShaddyMore    😃 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Descriptive commit messages 😄 
LInters checks passed ✔️ 
GitHub flow observed ✔️ 

## Required Changes ♻️
Kindly check the inline comments below for the required changes.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 11:01 UTC, OyePriscilla commented on index.html
> +          <img class="union" src="/images/Union.png" alt="Hamburger menu">
- [ ] Please kindly take note that all your images are not showing; you missed the dot (.) notation before the /.
Should be `<img class="union" src="./images/Union.png" alt="Hamburger menu">` not `<img class="union" src="/images/Union.png" alt="Hamburger menu">`. 😄 Please implement this for all your project images.

## Your Design
![127 0 0 1_5500_Mobile-Setup-Head-Middle_index html(mobile)](https://user-images.githubusercontent.com/103386183/199954638-5dd1ca98-0f65-487f-b72c-708fbecffcbe.png)

2022-11-04 11:01 UTC, OyePriscilla commented on index.html
> +              <div class="line-1"><hr></div>
- [ ] Kindly adjust this according to the design template.

## Your Design 

![b6](https://user-images.githubusercontent.com/103386183/199955119-63344c97-f199-4469-8976-820122722d45.png)


## Figma Design 

![crr7](https://user-images.githubusercontent.com/103386183/199955227-1d294036-a645-464d-8e66-110466c4c5a5.png)

2022-11-04 11:01 UTC, OyePriscilla commented on inde.html
> +            <h1 class="work-title">Tonic</h1>
- [ ] Kindly change this header tag to any other header tag (h2,h3 ...); it's part of best practices to have just one h1 tag in an HTML document purposely for SEO optimization. Please do this for all your cards and `About me `section as well. 😄

2022-11-04 19:31 UTC, bienvenuushindi requested changes
### Hi @ShaddyMore,

Good job implementing some of the required changes!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- [ ] N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-04 19:31 UTC, bienvenuushindi commented on index.html
> +              <h1 class="work-title">Multi-Post
:red_circle:  Please make sure you change this header tag to any other header tag (h2,h3 ...); As requested by the previous reviewer your HTML should not have more than one  `<h1> ` tag.  H1 on the page indicates what the entire web page is about. And the rest of the headings follow a hierarchical structure, with H2 for each topic section and any subsections to those being indicated with H3 and if the subtopic has subtopics then going down as low as H4.

I think this code should be `<h3 class="work-title">Multi-Post <br>Stories </h3>`

2022-11-04 19:31 UTC, bienvenuushindi commented on index.html
> +             <h1 class="work-title">Tonic </h1>
:red_circle:  Please make sure you change this header tag to any other header tag (h2,h3 ...); As requested by the previous reviewer your HTML should not have more than one  `<h1> ` tag.  H1 on the page indicates what the entire web page is about. And the rest of the headings follow a hierarchical structure, with H2 for each topic section and any subsections to those being indicated with H3 and if the subtopic has subtopics then going down as low as H4.

I think this code should be `<h3 class="work-title">Tonic </h3>`

2022-11-04 19:31 UTC, bienvenuushindi commented on index.html
> +             <h1 class="work-title">Multi-Post
:red_circle:  Please make sure you change this header tag to any other header tag (h2,h3 ...); As requested by the previous reviewer your HTML should not have more than one  `<h1> ` tag.  H1 on the page indicates what the entire web page is about. And the rest of the headings follow a hierarchical structure, with H2 for each topic section and any subsections to those being indicated with H3 and if the subtopic has subtopics then going down as low as H4.

I think this code should be `<h3 class="work-title">Multi-Post <br>Stories </h3>`

2022-11-04 19:31 UTC, bienvenuushindi commented on index.html
> +            <h1 class="work-title-1">Tonic</h1>
:red_circle:  Please make sure you change this header tag to any other header tag (h2,h3 ...); As requested by the previous reviewer your HTML should not have more than one  `<h1> ` tag.  H1 on the page indicates what the entire web page is about. And the rest of the headings follow a hierarchical structure, with H2 for each topic section and any subsections to those being indicated with H3 and if the subtopic has subtopics then going down as low as H4.

I think this code should be `<h3 class="work-title-1">Tonic</h3>`

2022-11-04 19:31 UTC, bienvenuushindi commented on index.html
> +            </li>
:red_circle: You have done well adjusting the languages block according to the design template :+1: . Please make sure you align correctly the Frameworks and Skills items to match the Figma Design

Your Design
![still](https://user-images.githubusercontent.com/26736582/200058272-c1186682-daac-4f3f-a61c-fff553f8f0cd.png)

Figma Design

![fima](https://user-images.githubusercontent.com/26736582/200058332-7c2e83ce-b5e5-4756-9535-795f59fe3287.png)

2022-11-04 19:31 UTC, bienvenuushindi commented on index.html
> +           </ul>
:red_circle:  As you can below none of these icons is displaying. You should keep one dot `.` before / to index the current directory. Kindly use one dot like this  `<img src=" ./icon-social/Github.png" alt="Github"/><a>` and not 
`<img src="../icon-social/Github.png" alt="Github"/><a>`. Please update all the images path under this  section :hugs: 

Your Design
![iconnotdispl](https://user-images.githubusercontent.com/26736582/200059478-3dfa82aa-4375-431f-93de-c2a332bb4145.png)

2022-11-05 17:33 UTC, Olamarx approved these changes
Hi @ShaddyMore, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights
- Good commit messages 👍🏼 
- All linters passed ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 19:12 UTC, merged